language: scala
scala:
- 2.11.7
- 2.10.5
jdk:
- oraclejdk7
- oraclejdk8
script: sbt ++${TRAVIS_SCALA_VERSION} test $(if [[ "${TRAVIS_PULL_REQUEST}" == "false"
  && ${JAVA_HOME} == $(jdk_switcher home oraclejdk7) && "${TRAVIS_BRANCH}" == "master"
  ]]; then echo "publish"; fi)
sudo: false
env:
  global:
  - secure: bf+aaECTxUQdZQhCWBKRHXONWO865gYax82mzQbPN/J+TA5l3+SxmVXuaWERPBjdDjFMrSzvqQwlk7i9yU6SMj1DqXJZDsbHbiL8PODf5Vc8OWW4RQv7Um/PDAhewk/Wk4qlKiMsWutU/VXSQpBlztp8WRsmS/5uif/qvV/YGHk=
  - secure: dXYe5w6njRYINrPOe3e+TwzS3svbLRGsaZtcbL4cgc/fZtpfX+Q60grzUoUWV0KS3HHzWyq8hOIoDKgsU2IRES9tF6z/gmObUHPXBHpn70+owm18BQniR48MksPWQvT7JTqZoE+VlS19LLVr3hw6sGeEsRGfAo8nfkIGqI7zwmQ=
